### ISSUE TITLE
Data questions

### ISSUE THREAD

**Issue by elephaint** [zalandoresearch/ACIC23-competition#3]
Hi,

Thanks for this competition - I've got some questions about the data that don't seem obvious from the description.

- The task is to predict for timesteps {1, ..., 5}. Does timestep 1 correspond to the first week after weekID 94? In other words, are you effectively asking to make forecasts for weekIDs {95, ..., 99} for every unit and every possible treatment?
- If the above is correct, am I also correct to assume no covariate information {X1, X2, ...., C3} on the forecast timesteps {1, ...., 5} is provided?
- Is the treatment variable an ordinal number? In other words, does it make sense to talk about the treatment in terms of '0.2' is more than '0.1'?
- For the covariates X1, X2, X3, similar as above: are these ordinal numbers or should I assume they are categorical?
- The outcome is greater or equal to zero in the training sample. Can I assume the outcome is always greater or equal to zero?

**Comment by elephaint** [comment]
@patrick-dd any update on this?

**Comment by patrick-dd** [comment]
Hi @elephaint, apologies for the delay!

> The task is to predict for timesteps {1, ..., 5}. Does timestep 1 correspond to the first week after weekID 94? In other words, are you effectively asking to make forecasts for weekIDs {95, ..., 99} for every unit and every possible treatment?

Correct

> If the above is correct, am I also correct to assume no covariate information {X1, X2, ...., C3} on the forecast timesteps {1, ...., 5} is provided?

Correct

> Is the treatment variable an ordinal number? In other words, does it make sense to talk about the treatment in terms of '0.2' is more than '0.1'?

Correct

> For the covariates X1, X2, X3, similar as above: are these ordinal numbers or should I assume they are categorical?

Open :)

> The outcome is greater or equal to zero in the training sample. Can I assume the outcome is always greater or equal to zero?

Yes, you can assume that.

Good luck!

**Comment by elephaint** [comment]
Thanks!
